[package]
name = "ckb-pow"
version = "0.25.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
byteorder = "1.3.1"
ckb-types = { path = "../util/types" }
serde = "1.0"
serde_derive = "1.0"
eaglesong = "0.1"

[dev-dependencies]
ckb-hash = { path = "../util/hash"}
