[package]
name = "ckb-indexer"
version = "0.25.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
ckb-types = { path = "../util/types" }
ckb-db = { path = "../db" }
ckb-shared = { path = "../shared" }
ckb-store = { path = "../store" }
ckb-jsonrpc-types = { path = "../util/jsonrpc-types" }
ckb-logger = { path = "../util/logger" }
ckb-util = { path = "../util" }

[dev-dependencies]
tempfile = "3.0"
ckb-chain =  { path = "../chain" }
ckb-chain-spec = { path = "../spec" }
ckb-resource = { path = "../resource" }
