[package]
name = "ckb-util"
version = "0.25.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
parking_lot = {version = "=0.7.1", features = ["deadlock_detection"]}
linked-hash-map = { git = "https://github.com/nervosnetwork/linked-hash-map", rev = "df27f21" }

[dev-dependencies]
ckb-fixed-hash = { path = "fixed-hash" }
